services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: docker-mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.xxx.xxx
    env_file: docker-mailserver/.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - 'mail_data_vol1:/var/mail/vol_1/'

      # For scalability, you can add more volumes for mail data.
      # In LDAP, you can create more mail users and assign them to different volumes.
      #- 'mail_data_vol2:/var/mail/vol_2/'

      - 'mail_state:/var/mail-state/'
      - 'mail_logs:/var/log/mail/'
      - 'mail_config:/tmp/docker-mailserver/'
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      - ldap_network
  ldap:
    restart: always
    build:
      context: ./openldap
    ports:
      - '389:1389'
      - '636:1636'
    env_file: openldap/.env
    networks:
      - ldap_network
    volumes:
      - /etc/letsencrypt/live/mail.xxx.xxx/privkey.pem:/opt/bitnami/openldap/certs/privkey.pem
      - /etc/letsencrypt/live/mail.xxx.xxx/fullchain.pem:/opt/bitnami/openldap/certs/fullchain.pem
      - 'openldap_data:/bitnami/openldap'
  phpldapadmin:
    restart: always
    hostname: mail.xxx.xxx
    image: osixia/phpldapadmin:latest
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap://ldap:1389
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "6443:80"
    networks:
      - ldap_network
networks:
  ldap_network:
    driver: bridge
volumes:
  mail_data_vol1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/volume_nyc1_01/mail_data
      # For scalability, you can add more volumes for mail data.
      # In LDAP, you can create more mail users and assign them to different volumes.
      #mail_data_vol2:
        #driver: local
        #driver_opts:
          #o: bind
          #type: none
          #device: /mnt/volume_2/mail_data
  mail_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/volume_nyc1_01/mail_config
  mail_state:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/volume_nyc1_01/mail_state
  mail_logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/volume_nyc1_01/mail_logs
  openldap_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/volume_nyc1_01/openldap