services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: docker-mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.xxx.xxx
    env_file: docker-mailserver/.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - 'mail_data_vol1:/var/mail/vol_1/'

      # For scalability, you can add more volumes for mail data.
      # In LDAP, you can create more mail users and assign them to different volumes.
      #- 'mail_data_vol2:/var/mail/vol_2/'

      - 'mail_state:/var/mail-state/'
      - 'mail_logs:/var/log/mail/'
      - 'mail_config:/tmp/docker-mailserver/'
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      - ldap_network
  ldap:
    restart: always
    build:
      context: ./openldap
    ports:
      - '389:1389'
      - '636:1636'
    env_file: openldap/.env
    networks:
      - ldap_network
    volumes:
      - /etc/letsencrypt/live/mail.xxx.xxx/privkey.pem:/opt/bitnami/openldap/certs/privkey.pem
      - /etc/letsencrypt/live/mail.xxx.xxx/fullchain.pem:/opt/bitnami/openldap/certs/fullchain.pem
      - 'openldap_data:/bitnami/openldap'
  phpldapadmin:
    restart: always
    hostname: mail.xxx.xxx
    image: osixia/phpldapadmin:latest
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap://ldap:1389
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "6443:80"
    networks:
      - ldap_network

# MONITORING
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.size=5GB"
    networks:
      - ldap_network
  nodeexporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    networks:
      - ldap_network
#  Uncomment the following lines if you want to monitor the host machine.
#  node_exporter:
#    image: quay.io/prometheus/node-exporter:latest
#    container_name: node_exporter
#    command:
#      - '--path.rootfs=/host'
#    network_mode: host
#    pid: host
#    restart: unless-stopped
#    volumes:
#      - '/:/host:ro,rslave'
  postfixscraper:
    build: ./postfix_scraper
    container_name: postfix_scraper
    env_file: postfix_scraper/.env
    restart: unless-stopped
    depends_on:
      - mailserver
    networks:
      - ldap_network
    volumes:
      - /mnt/volume_nyc1_01/mail_logs/mail.log:/var/log/mail.log:ro
      - ./postfix_scraper/postfix_scraper.py:/app/postfix_scraper.py
  ldapscraper:
    build: ./ldap_scraper
    container_name: ldap_scraper
    env_file: ldap_scraper/.env
    restart: unless-stopped
    depends_on:
      - mailserver
    networks:
      - ldap_network
    volumes:
      - 'mail_data_vol1:/var/mail/vol_1/'
      - ./ldap_scraper/ldap_scraper.py:/app/ldap_scraper.py
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - ldap_network
# MONITORING

networks:
  ldap_network:
    driver: bridge
volumes:
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/grafana
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/prometheus
  mail_data_vol1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/volume_nyc1_01/mail_data
      # For scalability, you can add more volumes for mail data.
      # In LDAP, you can create more mail users and assign them to different volumes.
      #mail_data_vol2:
        #driver: local
        #driver_opts:
          #o: bind
          #type: none
          #device: /mnt/volume_2/mail_data
  mail_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/volume_nyc1_01/mail_config
  mail_state:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/volume_nyc1_01/mail_state
  mail_logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/volume_nyc1_01/mail_logs
  openldap_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/volume_nyc1_01/openldap