global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'postfix_scraper'
    static_configs:
      - targets: ['postfixscraper:9555']

  - job_name: 'ldap_scraper'
    static_configs:
      - targets: ['ldapscraper:9777']